//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assets.Localization.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to close this tooltip.
        /// </summary>
        internal static string Tooltip_Jump_Hint {
            get {
                return ResourceManager.GetString("Tooltip_Jump_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Jump button to Jump.
        /// </summary>
        internal static string Tooltip_Jump_Title {
            get {
                return ResourceManager.GetString("Tooltip_Jump_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try moving a little.
        /// </summary>
        internal static string Tooltip_Movement_Hint {
            get {
                return ResourceManager.GetString("Tooltip_Movement_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the arrow keys, wasd or use a analog stick to move.
        /// </summary>
        internal static string Tooltip_Movement_Title {
            get {
                return ResourceManager.GetString("Tooltip_Movement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try it!.
        /// </summary>
        internal static string Tooltip_Onesie_Chicken_Hint {
            get {
                return ResourceManager.GetString("Tooltip_Onesie_Chicken_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This onesie lets you double jump.
        /// </summary>
        internal static string Tooltip_Onesie_Chicken_Title {
            get {
                return ResourceManager.GetString("Tooltip_Onesie_Chicken_Title", resourceCulture);
            }
        }
    }
}
